[package]
name = "dna_box"
version = "0.1.0"
authors = ["sivico26 <sivico26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
seq_io = "0.3.1"